apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myworld
  name: myworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myworld
    spec:
      containers:
      - image: demoaksacr2.azurecr.io/myworld
        name: myworld
        ports:
        - containerPort: 80
        resources: {}
status: {}
